services:
  pony2:
    image: pony2:latest
    build:
      context: .
      dockerfile: Dockerfile
      pull: true
    container_name: pony2
    restart: unless-stopped
    environment:
      PONY_TIMEZONE: "${PONY_TIMEZONE:-Europe/Berlin}"
      PONY_UID: "${PONY_UID:-1000}"
      PONY_GID: "${PONY_GID:-1000}"
    ports:
      - "8585:8080"
    volumes:
      - ./.pony2:/home/pony/.pony2 # Local data folder
      - ./music:/home/pony/music:ro # Music library folder
