# Logging
logging.file=${user.home}/.pony2/pony.log

# Datasource
spring.datasource.url=jdbc:h2:${user.home}/.pony2/db/pony
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.search.default.directory_provider=filesystem
spring.jpa.properties.hibernate.search.default.indexBase=${user.home}/.pony2/index
spring.jpa.properties.hibernate.search.lucene_version=LUCENE_CURRENT

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/management/h2

# Flyway
flyway.locations=db

# Management
management.context-path=/management

