# Pony
pony.home=${user.home}/.pony2
pony.artworkPath=${pony.home}/artwork

# Application
spring.main.banner-mode=off

# Logging
logging.file=${pony.home}/pony.log
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%p) %clr(${PID:- }){magenta} %clr([%t]){faint} %clr(%logger){cyan} %clr(:){faint} %m%n%wEx
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %p ${PID:- } [%t] %logger : %m%n%wEx

# Datasource
spring.datasource.url=jdbc:h2:${pony.home}/db/pony;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.search.default.directory_provider=filesystem
spring.jpa.properties.hibernate.search.default.indexBase=${pony.home}/index
spring.jpa.properties.hibernate.search.lucene_version=LUCENE_CURRENT

# Flyway
flyway.locations=classpath:db